### ISSUE TITLE
Can't install because it requires oauth-client 1.0 but I have 2.0

### ISSUE THREAD

**Issue by stevevance** [hayageek/oauth2-yahoo#4]
I believe the solution is to change the requirement in your package's `composer.json` field to allow for `league/oauth2-client` of version 2.0 or greater, but I can't test that. 

````
Using version ^2.0 for hayageek/oauth2-yahoo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install hayageek/oauth2-yahoo 2.0.4
    - Conclusion: don't install hayageek/oauth2-yahoo 2.0.2
    - Conclusion: don't install hayageek/oauth2-yahoo 2.0.1
    - Conclusion: remove league/oauth2-client 2.2.1
    - Installation request for hayageek/oauth2-yahoo ^2.0 -> satisfiable by hayageek/oauth2-yahoo[2.0.0, 2.0.1, 2.0.2, 2.0.4].
    - Conclusion: don't install league/oauth2-client 2.2.1
    - hayageek/oauth2-yahoo 2.0.0 requires league/oauth2-client ^1.0@dev -> satisfiable by league/oauth2-client[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2].
    - Can only install one of: league/oauth2-client[1.0.0, 2.2.1].
    - Can only install one of: league/oauth2-client[1.0.1, 2.2.1].
    - Can only install one of: league/oauth2-client[1.0.2, 2.2.1].
    - Can only install one of: league/oauth2-client[1.1.0, 2.2.1].
    - Can only install one of: league/oauth2-client[1.2.0, 2.2.1].
    - Can only install one of: league/oauth2-client[1.3.0, 2.2.1].
    - Can only install one of: league/oauth2-client[1.4.0, 2.2.1].
    - Can only install one of: league/oauth2-client[1.4.1, 2.2.1].
    - Can only install one of: league/oauth2-client[1.4.2, 2.2.1].
    - Installation request for league/oauth2-client (locked at 2.2.1) -> satisfiable by league/oauth2-client[2.2.1].


Installation failed, reverting ./composer.json to its original content.
````

**Comment by hayageek** [comment]
Let me test once.

**Comment by stevevance** [comment]
@hayageek Have you been able to test it?

**Comment by hayageek** [comment]
Yes.  Can you send me the project details &I command

**Comment by tru10000** [comment]
I'm experiencing the same issue.

`composer require hayageek/oauth2-yahoo
Using version ^2.0 for hayageek/oauth2-yahoo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hayageek/oauth2-yahoo 2.0.4 requires league/oauth2-client ^1.0 -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2] but these conflict with your requirements or minimum-stability.
    - hayageek/oauth2-yahoo 2.0.2 requires league/oauth2-client ^1.0@dev -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2] but these conflict with your requirements or minimum-stability.
    - hayageek/oauth2-yahoo 2.0.1 requires league/oauth2-client ^1.0@dev -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2] but these conflict with your requirements or minimum-stability.
    - hayageek/oauth2-yahoo 2.0.0 requires league/oauth2-client ^1.0@dev -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2] but these conflict with your requirements or minimum-stability.
    - Installation request for hayageek/oauth2-yahoo ^2.0 -> satisfiable by hayageek/oauth2-yahoo[2.0.0, 2.0.1, 2.0.2, 2.0.4].


Installation failed, reverting ./composer.json to its original content.`

**Comment by elieobeid7** [comment]
Same here, same issue

**Comment by inkxe-radhanatha** [comment]
I am facing the same issue. Please help me.

composer require hayageek/oauth2-yahoo
Using version ^2.0 for hayageek/oauth2-yahoo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hayageek/oauth2-yahoo 2.0.4 requires league/oauth2-client ^1.0 -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2] but these conflict with your requirements or minimum-stability.
    - hayageek/oauth2-yahoo 2.0.2 requires league/oauth2-client ^1.0@dev -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2] but these conflict with your requirements or minimum-stability.
    - hayageek/oauth2-yahoo 2.0.1 requires league/oauth2-client ^1.0@dev -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2] but these conflict with your requirements or minimum-stability.
    - hayageek/oauth2-yahoo 2.0.0 requires league/oauth2-client ^1.0@dev -> satisfiable by league/oauth2-client[1.0.0, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2] but these conflict with your requirements or minimum-stability.
    - Installation request for hayageek/oauth2-yahoo ^2.0 -> satisfiable by hayageek/oauth2-yahoo[2.0.0, 2.0.1, 2.0.2, 2.0.4].


Installation failed, reverting ./composer.json to its original content.

**Comment by inkxe-radhanatha** [comment]
@hayageek Still I am facing the same issue. Can you please help me?

![selection_015](https://user-images.githubusercontent.com/12268389/47779655-a1053d80-dd1f-11e8-95a5-60cb020eb033.png)
